//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace convee_web01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public string INVOICE_NUM { get; set; }
        public string CLIENT_NUMBER { get; set; }
        public string INVOICE_DATE { get; set; }
        public string PRICES_USED { get; set; }
        public Nullable<decimal> INVOICE_TOTAL { get; set; }
        public string PAYMENT_STATUS { get; set; }
        public string DELIVERY_STATUS { get; set; }
    }
}
