//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace convee_web01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public string PRD_CODE { get; set; }
        public string PRODUCT1 { get; set; }
        public string SELLING_PRICE { get; set; }
        public string WATERPRENEUR_PRICE { get; set; }
        public string WHOLESALE_PRICE { get; set; }
        public string PACK_SIZE { get; set; }
        public string PALLET_SIZE { get; set; }
        public string IMG_URL { get; set; }
        public string STOCK_LEVELS { get; set; }
    }
}
